package report

import (
    "encoding/json"
    "fmt"
    "os"

    "github.com/fatih/color"
    "github.com/Qyroxen/shieldguard/pkg/scanner"
)

type Reporter struct{}

func NewReporter() *Reporter {
    return &Reporter{}
}

func (r *Reporter) PrintSummary(vulns []scanner.Vulnerability) {
    if len(vulns) == 0 {
        color.New(color.FgGreen).Println("[+] No vulnerabilities detected. Your code is secure!")
        return
    }

    color.New(color.FgRed).Printf("[!] Found %d vulnerabilities:\n", len(vulns))
    for _, v := range vulns {
        color.New(color.FgYellow).Printf("  - %s:%d [%s] Severity: %s (score=%.2f)\n", v.FilePath, v.Line, v.Type, v.Severity, v.Score)
    }
    fmt.Println()
}

func (r *Reporter) PrintVulnerabilityWithFix(v scanner.Vulnerability, analysis string, patchText string) {
    color.New(color.FgHiCyan).Printf("==================================================\n")
    color.New(color.FgRed).Printf("Vulnerability: %s:%d (%s) [Severity: %s]\n", v.FilePath, v.Line, v.Type, v.Severity)
    color.New(color.FgWhite).Printf("Snippet: %s\n", v.Snippet)
    color.New(color.FgYellow).Printf("Analysis: %s\n", analysis)
    if patchText != "" {
        color.New(color.FgGreen).Printf("Suggested Fix:\n%s\n", patchText)
    }
    color.New(color.FgHiCyan).Printf("==================================================\n")
}

func (r *Reporter) ExportJSON(outputPath string, vulns []scanner.Vulnerability) error {
    data, err := json.MarshalIndent(vulns, "", "  ")
    if err != nil {
        return err
    }
    return os.WriteFile(outputPath, data, 0644)
}

func (r *Reporter) ExportHTML(outputPath string, vulns []scanner.Vulnerability) error {
    html := `<!DOCTYPE html>
<html>
<head>
    <title>ShieldGuard Security Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; background: #f4f6f9; color: #333; }
        h1 { color: #d9534f; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; background: #fff; }
        th, td { padding: 12px; border: 1px solid #ddd; text-align: left; }
        th { background: #343a40; color: #fff; }
        .CRITICAL { color: #d9534f; font-weight: bold; }
        .HIGH { color: #f0ad4e; font-weight: bold; }
    </style>
</head>
<body>
    <h1>ShieldGuard Security Scan Report</h1>
    <p>Generated by ShieldGuard v1.0.1 (Local-First SAST CLI)</p>
    <table>
        <tr>
            <th>File Path</th>
            <th>Line</th>
            <th>Type</th>
            <th>Severity</th>
            <th>Score</th>
            <th>Snippet</th>
        </tr>`

    for _, v := range vulns {
        html += fmt.Sprintf("<tr><td>%s</td><td>%d</td><td>%s</td><td class=\"%s\">%s</td><td>%.2f</td><td><code>%s</code></td></tr>",
            v.FilePath, v.Line, v.Type, v.Severity, v.Severity, v.Score, v.Snippet)
    }

    html += `
    </table>
</body>
</html>`

    return os.WriteFile(outputPath, []byte(html), 0644)
}