name: ShieldGuard CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Install Dependencies
        run: go mod download

      - name: Run Unit Tests
        run: go test -v -coverprofile=coverage.out ./...

      - name: Build Binary
        run: go build -v -o shieldguard main.go